from .CNN_Models.AlexNet.AlexNet_model import AlexNet
from .CNN_Models.ConvNext_family.ConvNext_base import ConvNext_Base
from .CNN_Models.ConvNext_family.ConvNext_large import ConvNext_Large
from .CNN_Models.ConvNext_family.ConvNext_small import ConvNext_Small
from .CNN_Models.ConvNext_family.ConvNext_tiny import ConvNext_Tiny
from .CNN_Models.MNASNet_family.MnasNet05 import MNASnet_05
from .CNN_Models.MNASNet_family.MnasNet075 import MNASnet_075
from .CNN_Models.MNASNet_family.MnasNet10 import MNASnet_10
from .CNN_Models.MNASNet_family.MnasNet13 import MNASnet_13
from .CNN_Models.GhostNet_family.Ghost_resnet import Ghost_ResNet
from .CNN_Models.GhostNet_family.GhostNetv2 import GhostNetV2
from .CNN_Models.Mobilenet_family.Mobilenetv1 import MobileNetV1
from .CNN_Models.Mobilenet_family.Mobilenetv2 import MobileNetV2
from .CNN_Models.Mobilenet_family.Mobilenetv3_small import mobilenet_v3_small
from .CNN_Models.Mobilenet_family.Mobilenetv3_large import mobilenet_v3_large
from .CNN_Models.ResNet_family.Resnet18 import ResNet18
from .CNN_Models.ResNet_family.Resnet34 import ResNet34
from .CNN_Models.ResNet_family.Resnet50 import ResNet50
from .CNN_Models.ResNet_family.Resnet101 import ResNet101
from .CNN_Models.ResNet_family.Resnet152 import ResNet152
from .CNN_Models.ResNet_family.Resnext50 import ResNext50
from .CNN_Models.ResNet_family.Resnext101 import ResNext101
from .CNN_Models.ResNet_family.wide_Resnet50 import wide_ResNet50
from .CNN_Models.ResNet_family.wide_Resnet101 import wide_ResNet101
from .CNN_Models.Squeezenet_family.Squeezenet_1_0 import SqueezeNet_1_0
from .CNN_Models.Squeezenet_family.Squeezenet_1_1 import SqueezeNet_1_1
from .CNN_Models.Efficientnet_family.efficientnet_b0 import EfficientNet_b0
from .CNN_Models.Efficientnet_family.efficientnet_b1 import EfficientNet_b1
from .CNN_Models.Efficientnet_family.efficientnet_b2 import EfficientNet_b2
from .CNN_Models.Efficientnet_family.efficientnet_b3 import EfficientNet_b3
from .CNN_Models.Efficientnet_family.efficientnet_b4 import EfficientNet_b4
from .CNN_Models.Efficientnet_family.efficientnet_b5 import EfficientNet_b5
from .CNN_Models.Efficientnet_family.efficientnet_b6 import EfficientNet_b6
from .CNN_Models.Efficientnet_family.efficientnet_b7 import EfficientNet_b7
from .CNN_Models.Efficientnet_family.efficientnet_v2_s import EfficientNet_v2_s
from .CNN_Models.Efficientnet_family.efficientnet_v2_m import EfficientNet_v2_m
from .CNN_Models.Efficientnet_family.efficientnet_v2_l import EfficientNet_v2_l
from .CNN_Models.Shufflenet_family.ShufflenetV2_x0_5 import ShuffleNetV2_x0_5
from .CNN_Models.Shufflenet_family.ShufflenetV2_x1_0 import ShuffleNetV2_x1_0
from .CNN_Models.Shufflenet_family.ShufflenetV2_x1_5 import ShuffleNetV2_x1_5
from .CNN_Models.Shufflenet_family.ShufflenetV2_x2_0 import ShuffleNetV2_x2_0
from .CNN_Models.Inception_Family.GoogleNet import GoogLeNet
from .CNN_Models.Inception_Family.Inception_bn import BNInception
from .CNN_Models.Inception_Family.Inception_resnet_v2 import Inception_Resnet_v2
from .CNN_Models.DenseNet_family.DenseNet121 import DenseNet_121
from .CNN_Models.DenseNet_family.DenseNet161 import DenseNet_161
from .CNN_Models.DenseNet_family.DenseNet169 import DenseNet_169
from .CNN_Models.DenseNet_family.DenseNet201 import DenseNet_201
from .CNN_Models.NFNet_Family.NFNet_f0 import NFNet_F0
from .CNN_Models.NFNet_Family.NFNet_f1 import NFNet_F1
from .CNN_Models.NFNet_Family.NFNet_f2 import NFNet_F2
from .CNN_Models.NFNet_Family.NFNet_f3 import NFNet_F3
from .CNN_Models.NFNet_Family.NFNet_f4 import NFNet_F4
from .CNN_Models.NFNet_Family.NFNet_f5 import NFNet_F5
from .CNN_Models.NFNet_Family.NFNet_f6 import NFNet_F6
from .CNN_Models.NFNet_Family.NFNet_f7 import NFNet_F7
from .CNN_Models.Vgg_family.Vgg11 import Vgg_11
from .CNN_Models.Vgg_family.Vgg11_BN import Vgg_11_bn
from .CNN_Models.Vgg_family.Vgg13 import Vgg_13
from .CNN_Models.Vgg_family.Vgg13_BN import Vgg_13_bn
from .CNN_Models.Vgg_family.Vgg16 import Vgg_16
from .CNN_Models.Vgg_family.Vgg16_BN import Vgg_16_bn
from .CNN_Models.Vgg_family.Vgg19 import Vgg_19
from .CNN_Models.Vgg_family.Vgg19_BN import Vgg_19_bn
from .CNN_Models.RegNet_family.Regnet_y_16gf import RegNet_y_16gf
from .CNN_Models.RegNet_family.Regnet_y_1_6gf import RegNet_y_1_6gf
from .CNN_Models.RegNet_family.Regnet_y_8gf import RegNet_y_8gf
from .CNN_Models.RegNet_family.Regnet_y_3_2gf import RegNet_y_3_2gf
from .CNN_Models.RegNet_family.Regnet_x_800mf import RegNet_x_800mf
from .CNN_Models.RegNet_family.Regnet_x_32gf import RegNet_x_32gf
from .CNN_Models.RegNet_family.Regnet_x_1_6gf import RegNet_x_1_6gf
from .CNN_Models.RegNet_family.Regnet_y_32gf import RegNet_y_32gf
from .CNN_Models.RegNet_family.Regnet_x_16gf import RegNet_x_16gf
from .CNN_Models.RegNet_family.Regnet_x_3_2gf import RegNet_x_3_2gf
from .CNN_Models.RegNet_family.Regnet_y_800mf import RegNet_y_800mf
from .CNN_Models.RegNet_family.Regnet_y_400mf import RegNet_y_400mf
from .CNN_Models.RegNet_family.Regnet_y_128gf import RegNet_y_128gf
from .CNN_Models.RegNet_family.Regnet_x_8gf import RegNet_x_8gf
from .CNN_Models.RegNet_family.Regnet_x_400mf import RegNet_x_400mf
from .ViT_Models.Twins_family.Twins_svt_large import Twins_SVT_Large
from .ViT_Models.Twins_family.Twins_svt_base import Twins_SVT_Base
from .ViT_Models.Twins_family.Twins_svt_small import Twins_SVT_Small
from .ViT_Models.Twins_family.Twins_pcpvt_Small import Twins_PCPVT_Small
from .ViT_Models.Twins_family.Twins_pcpvt_Base import Twins_PCPVT_Base
from .ViT_Models.Twins_family.Twins_pcpvt_large import Twins_PCPVT_Large
from .ViT_Models.FocalTransformer_Family.FocalTransformer_base import FocalTransformer_Base
from .ViT_Models.FocalTransformer_Family.FocalTransformer_tiny import FocalTransformer_Tiny
from .ViT_Models.FocalTransformer_Family.FocalTransformer_small import FocalTransformer_Small
from .ViT_Models.PoolFormer_Family.PoolFormer_m36 import PoolFormer_M36
from .ViT_Models.PoolFormer_Family.PoolFormer_m48 import PoolFormer_M48
from .ViT_Models.PoolFormer_Family.PoolFormer_s12 import PoolFormer_S12
from .ViT_Models.PoolFormer_Family.PoolFormer_s24 import PoolFormer_S24
from .ViT_Models.PoolFormer_Family.PoolFormer_s36 import PoolFormer_S36
from .ViT_Models.SepViT_family.Sep_ViT_tiny import Sep_ViT_Tiny
from .ViT_Models.SepViT_family.Sep_ViT_small import Sep_ViT_Small
from .ViT_Models.SepViT_family.Sep_ViT_lite import Sep_ViT_Lite
from .ViT_Models.SepViT_family.Sep_ViT_base import Sep_ViT_Base
from .ViT_Models.Max_ViT_Family.maxvit import MaxVit_tiny
from .ViT_Models.VAN_Family.VAN_b0_model import VAN_b0
from .ViT_Models.VAN_Family.VAN_b1_model import VAN_b1
from .ViT_Models.VAN_Family.VAN_b2_model import VAN_b2
from .ViT_Models.VAN_Family.VAN_b3_model import VAN_b3
from .ViT_Models.VAN_Family.VAN_b4_model import VAN_b4
from .ViT_Models.VAN_Family.VAN_b5_model import VAN_b5
from .ViT_Models.VAN_Family.VAN_b6_model import VAN_b6
from .ViT_Models.CaiT_family.CaiT_xxs24 import CaiT_XXS24
from .ViT_Models.CaiT_family.CaiT_xxs36 import CaiT_XXS36
from .ViT_Models.CaiT_family.CaiT_xs24 import CaiT_XS24
from .ViT_Models.CaiT_family.CaiT_xs36 import CaiT_XS36
from .ViT_Models.CaiT_family.CaiT_s24 import CaiT_S24
from .ViT_Models.CaiT_family.CaiT_s36 import CaiT_S36
from .ViT_Models.BoTNet_Family.BoTNet_model import BoTNet
from .ViT_Models.LVT_Family.LVT_model import LVT
from .ViT_Models.DeepViT_family.DeepViT16 import DeepViT_16
from .ViT_Models.DeepViT_family.DeepViT24 import DeepViT_24
from .ViT_Models.DeepViT_family.DeepViT32 import DeepViT_32
from .ViT_Models.DeepViT_family.DeepViTL import DeepViT_L
from .ViT_Models.DeepViT_family.DeepViTS import DeepViT_S
from .ViT_Models.GC_ViT_Family.gc_vit_small import GCViT_Small
from .ViT_Models.GC_ViT_Family.gc_vit_small2 import GCViT_Small2
from .ViT_Models.GC_ViT_Family.gc_vit_base import GCViT_Base
from .ViT_Models.GC_ViT_Family.gc_vit_large import GCViT_Large
from .ViT_Models.GC_ViT_Family.gc_vit_xxtiny import GCViT_xxTiny
from .ViT_Models.GC_ViT_Family.gc_vit_xtiny import GCViT_xTiny
from .ViT_Models.GC_ViT_Family.gc_vit_tiny import GCViT_Tiny
from .ViT_Models.GC_ViT_Family.gc_vit_tiny2 import GCViT_Tiny2
from .ViT_Models.Swin_family.Swin_ViT_tiny import Swin_ViT_Tiny
from .ViT_Models.Swin_family.Swin_ViT_small import Swin_ViT_Small
from .ViT_Models.Swin_family.Swin_ViT_base import Swin_ViT_Base
from .ViT_Models.Swin_family.Swin_ViT_tiny_window7 import Swin_ViT_Tiny_window7
from .ViT_Models.Swin_family.Swin_ViT_small_window7 import Swin_ViT_Small_window7
from .ViT_Models.Swin_family.Swin_ViT_base_window7 import Swin_ViT_Base_window7
from .ViT_Models.Swin_family.Swin_ViT_large_window7 import Swin_ViT_Large_window7
from .ViT_Models.EdgeNeXt_Family.EdgeNeXt_BNHS_xsmall import EdgeNeXt_BNHS_Xsmall
from .ViT_Models.EdgeNeXt_Family.EdgeNeXt_BNHS_small import EdgeNeXt_BNHS_Small
from .ViT_Models.EdgeNeXt_Family.EdgeNeXt_xsmall import EdgeNeXt_Xsmall
from .ViT_Models.EdgeNeXt_Family.EdgeNeXt_small import EdgeNeXt_Small
from .ViT_Models.EdgeNeXt_Family.EdgeNeXt_base import EdgeNeXt_Base
from .ViT_Models.EdgeNeXt_Family.EdgeNeXt_BNHS_xxsmall import EdgeNeXt_BNHS_Xxsmall
from .ViT_Models.MobileFormer_Family.MobileFormer_26m import MobileFormer_26M
from .ViT_Models.MobileFormer_Family.MobileFormer_52m import MobileFormer_52M
from .ViT_Models.MobileFormer_Family.MobileFormer_96m import MobileFormer_96M
from .ViT_Models.MobileFormer_Family.MobileFormer_151m import MobileFormer_151M
from .ViT_Models.MobileFormer_Family.MobileFormer_214m import MobileFormer_214M
from .ViT_Models.MobileFormer_Family.MobileFormer_294m import MobileFormer_294M
from .ViT_Models.MobileFormer_Family.MobileFormer_508m import MobileFormer_508M
from .ViT_Models.CCT_family.CCT_model_7 import CCT_7
from .ViT_Models.CCT_family.CCT_model_7_sine import CCT_7_sine
from .ViT_Models.CCT_family.CCT_model_14 import CCT_14
from .ViT_Models.CCT_family.CCT_model_14_sine import CCT_14_sine
from .ViT_Models.TNT_family.TNT_base import TNT_Base
from .ViT_Models.TNT_family.TNT_small import TNT_Small
from .ViT_Models.Vision_transformer.ViT_tiny_patch16 import ViT_Tiny_patch16
from .ViT_Models.Vision_transformer.ViT_small_patch8 import ViT_Small_patch8
from .ViT_Models.Vision_transformer.ViT_small_patch16 import ViT_Small_patch16
from .ViT_Models.Vision_transformer.ViT_small_patch32 import ViT_Small_patch32
from .ViT_Models.Vision_transformer.ViT_base_patch8 import ViT_Base_patch8
from .ViT_Models.Vision_transformer.ViT_base_patch16 import ViT_Base_patch16
from .ViT_Models.Vision_transformer.ViT_base_patch32 import ViT_Base_patch32
from .ViT_Models.Vision_transformer.ViT_large_patch14 import ViT_Large_patch14
from .ViT_Models.Vision_transformer.ViT_large_patch16 import ViT_Large_patch16
from .ViT_Models.Vision_transformer.ViT_large_patch32 import ViT_Large_patch32
from .ViT_Models.Vision_transformer.ViT_huge_patch14 import ViT_Huge_patch14
from .ViT_Models.Vision_transformer.ViT_giant_patch14 import ViT_Giant_patch14
from .ViT_Models.Vision_transformer.ViT_gigantic_patch14 import ViT_Gigantic_patch14
from .ViT_Models.MLP_Mixer_Family.MLP_Mixer import MLPMixer
from .ViT_Models.MLP_Mixer_Family.ResMLP_model import ResMLP
from .ViT_Models.Efficientformer_family.Efficientformer_L1 import EfficientFormer_L1
from .ViT_Models.Efficientformer_family.Efficientformer_L3 import EfficientFormer_L3
from .ViT_Models.Efficientformer_family.Efficientformer_L7 import EfficientFormer_L7
from .ViT_Models.Efficientformer_family.EfficientformerV2_L import EfficientFormerV2_L
from .ViT_Models.Efficientformer_family.EfficientformerV2_S1 import EfficientFormerV2_S1
from .ViT_Models.Efficientformer_family.EfficientformerV2_S0 import EfficientFormerV2_S0
from .ViT_Models.Efficientformer_family.EfficientformerV2_S2 import EfficientFormerV2_S2
from .ViT_Models.T2T_family.T2T_ViT_T_24_model import T2T_ViT_T_24
from .ViT_Models.T2T_family.T2T_ViT_T_14_model import T2T_ViT_T_14
from .ViT_Models.T2T_family.T2T_ViT_12_model import T2T_ViT_12
from .ViT_Models.T2T_family.T2T_ViT_14_model import T2T_ViT_14
from .ViT_Models.T2T_family.T2T_ViT_7_model import T2T_ViT_7
from .ViT_Models.T2T_family.T2T_ViT_24_model import T2T_ViT_24
from .ViT_Models.T2T_family.T2T_ViT_14_resnext_model import T2T_ViT_14_resnext
from .ViT_Models.T2T_family.T2T_ViT_10_model import T2T_ViT_10
from .ViT_Models.T2T_family.T2T_ViT_14_wide_model import T2T_ViT_14_wide
from .ViT_Models.T2T_family.T2T_ViT_T_19_model import T2T_ViT_T_19
from .ViT_Models.T2T_family.T2T_ViT_19_model import T2T_ViT_19
from .ViT_Models.Region_ViT_family.RegionViT_small_w14_peg import RegionViT_Small_w14_peg
from .ViT_Models.Region_ViT_family.RegionViT_medium import RegionViT_Medium
from .ViT_Models.Region_ViT_family.RegionViT_small import RegionViT_Small
from .ViT_Models.Region_ViT_family.RegionViT_base_w14_peg import RegionViT_Base_w14_peg
from .ViT_Models.Region_ViT_family.RegionViT_tiny import RegionViT_Tiny
from .ViT_Models.Region_ViT_family.RegionViT_base import RegionViT_Base
from .ViT_Models.Region_ViT_family.RegionViT_small_w14 import RegionViT_Small_w14
from .ViT_Models.Region_ViT_family.RegionViT_base_w14 import RegionViT_Base_w14
from .ViT_Models.CrossViT_family.CrossViT15 import CrossViT_15
from .ViT_Models.CrossViT_family.CrossViT15_dagger import CrossViT_15_dagger
from .ViT_Models.CrossViT_family.CrossViT18 import CrossViT_18
from .ViT_Models.CrossViT_family.CrossViT9 import CrossViT_9
from .ViT_Models.CrossViT_family.CrossViT9_dagger import CrossViT_9_dagger
from .ViT_Models.CrossViT_family.CrossViT_base import CrossViT_Base
from .ViT_Models.CrossViT_family.CrossViT_tiny import CrossViT_Tiny
from .ViT_Models.CrossViT_family.CrossViT_small import CrossViT_Small
from .ViT_Models.CrossFormer_family.Crossformer_tiny import CrossFormer_tiny
from .ViT_Models.CrossFormer_family.Crossformer_small import CrossFormer_small
from .ViT_Models.CrossFormer_family.Crossformer_base import CrossFormer_base
from .ViT_Models.CrossFormer_family.Crossformer_large import CrossFormer_large
from .ViT_Models.PVT_Family.PvT_v2_b0_model import PvT_v2_b0
from .ViT_Models.PVT_Family.PvT_v2_b1_model import PvT_v2_b1
from .ViT_Models.PVT_Family.PvT_v2_b2_model import PvT_v2_b2
from .ViT_Models.PVT_Family.PvT_v2_b3_model import PvT_v2_b3
from .ViT_Models.PVT_Family.PvT_v2_b4_model import PvT_v2_b4
from .ViT_Models.PVT_Family.PvT_v2_b5_model import PvT_v2_b5
from .ViT_Models.PVT_Family.PvT_v2_b2_linear_model import PvT_v2_b2_Linear
from .ViT_Models.PVT_Family.PvT_small import PvT_Small
from .ViT_Models.PVT_Family.PvT_tiny import PvT_Tiny
from .ViT_Models.PVT_Family.PvT_medium import PvT_Medium
from .ViT_Models.PVT_Family.PvT_large import PvT_Large
from .ViT_Models.PVT_Family.PvT_huge_v2 import PvT_Huge_v2
from .ViT_Models.LeViT_family.LeViT_model_128s import LeViT_128S
from .ViT_Models.LeViT_family.LeViT_model_128 import LeViT_128
from .ViT_Models.LeViT_family.LeViT_model_192 import LeViT_192
from .ViT_Models.LeViT_family.LeViT_model_256 import LeViT_256
from .ViT_Models.LeViT_family.LeViT_model_384 import LeViT_384
from .ViT_Models.CvT_family.CvT_21_Model import CvT_21
from .ViT_Models.CvT_family.CvT_13_Model import CvT_13
from .ViT_Models.PiT_family.PiT_small import PiT_Small
from .ViT_Models.PiT_family.PiT_xs import PiT_XS
from .ViT_Models.PiT_family.PiT_base import PiT_Base
from .ViT_Models.PiT_family.PiT_ti import PiT_TI